from collections import defaultdict

# HDF5 version info
FILETYPE_REACTOR_H5 = 'output'
VERSION_REACTOR_H5 = 2
FILETYPE_DEPLETION_LIBRARY = 'depletion_data'
VERSION_DEPLETION_LIBRARY = 5

# Enumerations for whether a material is in-core, in storage, or
# considered as a supply source
IN_CORE = 0
STORAGE = 1
SUPPLY = 2
ALLOWED_STATUSES = [IN_CORE, STORAGE, SUPPLY]
STATUS_STRING = {IN_CORE: "in-core", STORAGE: "storage", SUPPLY: "supply"}

DEFAULT_H5_OUTPUT = "results.h5"
STEP_FNAME = "case_{}_op_{}_step_{}"
HDF_GROUPNAME = "case_{}/operation_{}/step_{}"

BASE_LIB = 0
VALID_DEPLETION_METHODS = ["predictor", "cecm"]
DEFAULT_DEPLETION_METHOD = "cecm"
DEFAULT_DEPLETING = True
VALID_OPERATIONS_SECTIONS = ["deplete", "shuffle", "transform", "write_input"]
VALID_MOVE_TYPES = defaultdict(lambda: ["material"])
VALID_MOVE_TYPES["mcnp"] = ["material", "universe"]
DEFAULT_MOVE_TYPE = defaultdict(lambda: "material")
VALID_TRANSFORM_TYPES = defaultdict(lambda: None)
VALID_TRANSFORM_TYPES["mcnp"] = ["universe", "cell", "surface"]
DEFAULT_TRANSFORM_TYPE = defaultdict(lambda: None)
DEFAULT_TRANSFORM_TYPE["mcnp"] = "universe"
DEFAULT_LIBRARY_DUMP_ALL = "all_modified"
VALID_GEOM_SWEEP_TYPES = ["surface"]
VALID_GEOM_SWEEP_AXES = ["x", "y", "z", "pitch", "yaw", "roll"]
DEFAULT_GEOM_SWEEP_RANGE_ENDPOINT = True
VALID_ANGLE_TYPES = ["degrees", "radians"]
DEFAULT_ANGLE_TYPE = "degrees"
DEFAULT_GEOM_SEARCH_MAX_ITERATIONS = 30
DEFAULT_GEOM_SEARCH_MIN_ACTIVE_BATCHES = 30
DEFAULT_GEOM_SEARCH_UNCERTAINTY_FRACTION = 0.6
DEFAULT_REACTIVITY_THRESH = 0.0
DEFAULT_REACTIVITY_THRESH_TO_INITIAL = False


# Define the possible types of neutronics solvers
NEUTRONICS_SOLVER_TYPES = ["mcnp", "test"]

# Define the possible types of depletion solvers
DEPLETION_SOLVER_TYPES = ["origen2.2", "cram16", "cram48", "test", "msr",
                          "msr16", "msr48"]
INTERNAL_DEPLETION_SOLVERS = ["cram16", "cram48", "test", "msr", "msr16",
                              "msr48"]

# Whether to use the depletion library cross sections or create own
USE_DEPLETION_LIBRARY_XS = True
DEFAULT_MATL_USE_DEFAULT_DEPL_LIB = False
MATL_MAX_ID = 99999999

TIME_STRINGF = "%Y-%m-%d %H:%M:%S"

DEFAULT_DENSITY = 1.0

DEFAULT_VOL_TARGET_UNC = 1.E-3  # In units of percent
DEFAULT_VOL_MAX_HIST = int(10E9)  # Set to 10 billion histories

# Values here are from the Committee on Data for Science and Technology
# (CODATA) 2014 recommendation (doi:10.1103/RevModPhys.88.035009).

# The value of the Boltzman constant in units of eV / K
K_BOLTZMANN = 8.6173303e-5

# Unit conversions
EV_PER_MEV = 1.0e6
JOULE_PER_EV = 1.6021766208e-19

# Avogadro's constant
AVOGADRO = 6.022140857e23

# Neutron mass in units of amu
NEUTRON_MASS = 1.00866491588

# The relative precision of volumes to require when doing fuel mgmt
VOLUME_PRECISION = 1.E-3

# Maximum metastable level assumed to exist in a data library
# This is required because removed versions of isotopes will have
# this added to their metastable state
MAX_METASTABLE_STATE = 10

# The methods available to solve the MSR system
MSR_SOLN_METHODS = ["brute", "tmatrix", "tmatrix_expm",
                    "rxn_rate_avg"]

# The default method for solving MSRs
MSR_DEFAULT_SOLN_METHOD = "tmatrix"

ORIGEN_ISO_DECAY_TYPES_FROM_SRC = {
    'Er162': ['activation'],
    'Ce136': ['activation'],
    'Ba150': ['fp'],
    'Sn117': ['activation', 'fp'],
    'Gd155_m1': ['activation', 'fp'],
    'Zr104': ['fp'],
    'Dy157': ['activation'],
    'Ga73': ['fp'],
    'As83': ['fp'],
    'Cs142': ['fp'],
    'Sb125': ['activation', 'fp'],
    'Ge85': ['fp'],
    'Kr92': ['fp'],
    'Sn127_m1': ['fp'],
    'Tc111': ['fp'],
    'Rn219': ['actinide'],
    'Gd154': ['activation', 'fp'],
    'Gd160': ['activation', 'fp'],
    'Mo93': ['activation'],
    'Ir194_m1': ['activation'],
    'Rb90': ['fp'],
    'Mo102': ['fp'],
    'Er163': ['activation'],
    'Pb211': ['actinide'],
    'Sr100': ['fp'],
    'Se82': ['activation', 'fp'],
    'Cs147': ['fp'],
    'Mg27': ['activation'],
    'Pd109': ['activation', 'fp'],
    'Sc47': ['activation'],
    'Fe58': ['activation'],
    'Pd104': ['activation', 'fp'],
    'Pu240': ['actinide'],
    'Ba143': ['fp'],
    'Hg204': ['activation'],
    'Tc108': ['fp'],
    'Kr91': ['fp'],
    'Ag126': ['fp'],
    'Th230': ['actinide'],
    'Se77_m1': ['activation', 'fp'],
    'Pt197': ['activation'],
    'Se92': ['fp'],
    'La137': ['activation'],
    'W186': ['activation'],
    'Ba152': ['fp'],
    'Rh115': ['fp'],
    'Ra228': ['actinide'],
    'Cs135_m1': ['fp'],
    'Fe59': ['activation'],
    'Br93': ['fp'],
    'Ni75': ['fp'],
    'Sm159': ['fp'],
    'Sm148': ['activation', 'fp'],
    'Cd128': ['fp'],
    'Am243': ['actinide'],
    'Zn71_m1': ['activation', 'fp'],
    'Ge86': ['fp'],
    'Tb165': ['fp'],
    'Rh123': ['fp'],
    'Dy166': ['activation', 'fp'],
    'La138': ['activation', 'fp'],
    'Er168': ['activation', 'fp'],
    'Zr105': ['fp'],
    'Pr154': ['fp'],
    'Pr143': ['activation', 'fp'],
    'In117': ['activation', 'fp'],
    'Sn122': ['activation', 'fp'],
    'W188': ['activation'],
    'Sr93': ['activation', 'fp'],
    'Tl203': ['activation'],
    'Br82_m1': ['activation', 'fp'],
    'Tb159': ['activation', 'fp'],
    'Be11': ['activation'],
    'Ba133': ['activation', 'fp'],
    'Yb171': ['activation', 'fp'],
    'Si30': ['activation'],
    'W185_m1': ['activation'],
    'Be8': ['activation'],
    'Nd145': ['activation', 'fp'],
    'Pd110': ['activation', 'fp'],
    'Sm147': ['activation', 'fp'],
    'Tc99_m1': ['fp'],
    'Rh109_m1': ['fp'],
    'Rb89': ['activation', 'fp'],
    'Ni58': ['activation'],
    'I136': ['fp'],
    'Nd147': ['activation', 'fp'],
    'Cf250': ['actinide'],
    'P32': ['activation'],
    'Sn113_m1': ['activation'],
    'Sb130': ['fp'],
    'Ba136': ['activation', 'fp'],
    'Nd159': ['fp'],
    'Cu77': ['fp'],
    'Eu149': ['fp'],
    'Cd111_m1': ['activation', 'fp'],
    'I141': ['fp'],
    'Mn57': ['activation'],
    'Fe55': ['activation'],
    'Os184': ['activation'],
    'Te127': ['activation', 'fp'],
    'Sb131': ['fp'],
    'Nb101': ['fp'],
    'Al29': ['activation'],
    'Ag110_m1': ['activation', 'fp'],
    'Pr144_m1': ['fp'],
    'Ca41': ['activation'],
    'K44': ['activation'],
    'Lu176_m1': ['activation'],
    'Sn136': ['fp'],
    'Th227': ['actinide'],
    'Tm170': ['activation', 'fp'],
    'Ca48': ['activation'],
    'Pm156': ['fp'],
    'Ag109_m1': ['activation', 'fp'],
    'Sb130_m1': ['fp'],
    'Se79': ['activation', 'fp'],
    'C13': ['activation'],
    'Pb207': ['actinide', 'activation'],
    'Kr95': ['fp'],
    'Rb96': ['fp'],
    'Sn113': ['activation'],
    'Se91': ['fp'],
    'Bi208': ['actinide', 'activation'],
    'Cm241': ['actinide'],
    'Cs134_m1': ['activation', 'fp'],
    'Sr95': ['fp'],
    'Cd110': ['activation', 'fp'],
    'La148': ['fp'],
    'Cf255': ['actinide'],
    'Kr81_m1': ['activation', 'fp'],
    'Cd120': ['fp'],
    'Pm161': ['fp'],
    'Po210': ['actinide', 'activation'],
    'Nd152': ['fp'],
    'Y101': ['fp'],
    'Tc115': ['fp'],
    'Sb126_m1': ['activation', 'fp'],
    'Tb164': ['fp'],
    'Pr159': ['fp'],
    'Pm153': ['fp'],
    'Sc46': ['activation'],
    'Ce145': ['activation', 'fp'],
    'In126': ['fp'],
    'Tl204': ['activation'],
    'Te123': ['activation', 'fp'],
    'La151': ['fp'],
    'Cu72': ['fp'],
    'Xe132': ['activation', 'fp'],
    'Mo110': ['fp'],
    'Bk251': ['actinide'],
    'Rb87': ['activation', 'fp'],
    'Pb209': ['actinide', 'activation'],
    'Ga78': ['fp'],
    'I138': ['fp'],
    'Hf178': ['activation'],
    'Br85': ['fp'],
    'Rh104_m1': ['activation', 'fp'],
    'Sr94': ['fp'],
    'Cl36': ['activation'],
    'Os185': ['activation'],
    'Pb214': ['actinide'],
    'Sm161': ['fp'],
    'Ni77': ['fp'],
    'Sb123': ['activation', 'fp'],
    'Pm152_m1': ['fp'],
    'Sb134': ['fp'],
    'Hf179': ['activation'],
    'Zr91': ['activation', 'fp'],
    'Ga71': ['activation', 'fp'],
    'Ga74': ['fp'],
    'Pt193': ['activation'],
    'Xe124': ['activation'],
    'Bi210_m1': ['actinide', 'activation'],
    'Mo92': ['activation'],
    'In123_m1': ['fp'],
    'Hf180': ['activation'],
    'Ce138': ['activation'],
    'Kr85_m1': ['activation', 'fp'],
    'F20': ['activation'],
    'Nb100_m1': ['fp'],
    'Yb168': ['activation', 'fp'],
    'K43': ['activation'],
    'Br80': ['activation', 'fp'],
    'Sn135': ['fp'],
    'Dy164': ['activation', 'fp'],
    'Ru114': ['fp'],
    'Tb157': ['activation'],
    'Am241': ['actinide'],
    'Mo94': ['activation'],
    'Ac225': ['actinide'],
    'Ta183': ['activation'],
    'O17': ['activation'],
    'Rh103': ['activation', 'fp'],
    'Pb212': ['actinide'],
    'Tc102': ['fp'],
    'Sb134_m1': ['fp'],
    'Pr147': ['fp'],
    'U235': ['actinide'],
    'In124': ['fp'],
    'K40': ['activation'],
    'Pr157': ['fp'],
    'Ar42': ['activation'],
    'Co58': ['activation'],
    'Xe146': ['fp'],
    'Sm160': ['fp'],
    'Gd159': ['activation', 'fp'],
    'Eu153': ['activation', 'fp'],
    'Pt199': ['activation'],
    'Zn64': ['activation'],
    'C12': ['activation'],
    'Zr96': ['activation', 'fp'],
    'I135': ['fp'],
    'Sm157': ['fp'],
    'Nb99_m1': ['fp'],
    'F19': ['activation'],
    'Am244': ['actinide'],
    'Xe135_m1': ['activation', 'fp'],
    'Os191_m1': ['activation'],
    'Ga85': ['fp'],
    'Ga76': ['fp'],
    'Sn131': ['fp'],
    'Cr54': ['activation'],
    'Mo106': ['fp'],
    'Rh110': ['fp'],
    'Y104': ['fp'],
    'Ge78': ['fp'],
    'Rh112': ['fp'],
    'Sb132': ['fp'],
    'Cl37': ['activation'],
    'W182': ['activation'],
    'Tc104': ['fp'],
    'S37': ['activation'],
    'Pd111': ['activation', 'fp'],
    'Ge73_m1': ['fp'],
    'As78': ['fp'],
    'La154': ['fp'],
    'Te125_m1': ['activation', 'fp'],
    'Pr150': ['fp'],
    'Zn67': ['activation', 'fp'],
    'Nb110': ['fp'],
    'N14': ['activation'],
    'Nb107': ['fp'],
    'Ru105': ['activation', 'fp'],
    'Ca40': ['activation'],
    'Ba144': ['fp'],
    'Ca47': ['activation'],
    'Zn81': ['fp'],
    'Ce140': ['activation', 'fp'],
    'Se86': ['fp'],
    'As89': ['fp'],
    'Nd143': ['activation', 'fp'],
    'Ba146': ['fp'],
    'Nd148': ['activation', 'fp'],
    'Pr141': ['activation', 'fp'],
    'Cd115_m1': ['activation', 'fp'],
    'Pa234_m1': ['actinide'],
    'As77': ['activation', 'fp'],
    'Sn125': ['activation', 'fp'],
    'Rh121': ['fp'],
    'V54': ['activation'],
    'Os194': ['activation'],
    'In125_m1': ['fp'],
    'La141': ['activation', 'fp'],
    'Nb93': ['activation', 'fp'],
    'Ag117': ['fp'],
    'Sc46_m1': ['activation'],
    'Nd157': ['fp'],
    'Eu165': ['fp'],
    'Xe129': ['activation', 'fp'],
    'Ra224': ['actinide'],
    'Eu152': ['activation', 'fp'],
    'Sm164': ['fp'],
    'Ru98': ['activation'],
    'Ag114': ['fp'],
    'Se87': ['fp'],
    'Ag115': ['fp'],
    'Os190': ['activation'],
    'Se93': ['fp'],
    'Ta180': ['activation'],
    'Ge70': ['activation', 'fp'],
    'Rh106': ['activation', 'fp'],
    'Zn78': ['fp'],
    'Br86_m1': ['fp'],
    'Au199': ['activation'],
    'Sm156': ['fp'],
    'Zr93': ['activation', 'fp'],
    'Re188': ['activation'],
    'Kr90': ['fp'],
    'Xe125_m1': ['activation'],
    'Ba145': ['fp'],
    'Ti50': ['activation'],
    'Er170': ['activation', 'fp'],
    'Kr93': ['fp'],
    'Cs138': ['activation', 'fp'],
    'Cs149': ['fp'],
    'Np241': ['actinide'],
    'Er172': ['activation', 'fp'],
    'Dy158': ['activation'],
    'W181': ['activation'],
    'Cu75': ['fp'],
    'Ge83': ['fp'],
    'Rb86_m1': ['activation', 'fp'],
    'Eu161': ['fp'],
    'Sr86': ['activation', 'fp'],
    'I134': ['fp'],
    'Ba151': ['fp'],
    'Yb175_m1': ['activation'],
    'Cm244': ['actinide'],
    'Cm245': ['actinide'],
    'Kr83': ['activation', 'fp'],
    'Xe129_m1': ['activation', 'fp'],
    'Eu162': ['fp'],
    'Mo107': ['fp'],
    'Nb102': ['fp'],
    'Tb162': ['activation', 'fp'],
    'Sr97': ['fp'],
    'Ba137': ['activation', 'fp'],
    'Cd132': ['fp'],
    'Ni60': ['activation'],
    'Pb206': ['actinide', 'activation'],
    'I145': ['fp'],
    'H1': ['activation'],
    'Bk249': ['actinide'],
    'Te139': ['fp'],
    'Eu163': ['fp'],
    'Ga75': ['fp'],
    'Sr85_m1': ['activation'],
    'In131': ['fp'],
    'Cr52': ['activation'],
    'Dy165_m1': ['activation', 'fp'],
    'Ru97': ['activation'],
    'La145': ['fp'],
    'Pb204': ['activation'],
    'Er167': ['activation', 'fp'],
    'I136_m1': ['fp'],
    'Mo113': ['fp'],
    'Cd124': ['fp'],
    'Ru109': ['fp'],
    'Cu65': ['activation'],
    'C15': ['activation'],
    'As84': ['fp'],
    'Mo103': ['fp'],
    'Sr96': ['fp'],
    'Nd154': ['fp'],
    'Sn129_m1': ['fp'],
    'Ge88': ['fp'],
    'Co58_m1': ['activation'],
    'Mn55': ['activation'],
    'Yb174': ['activation'],
    'Hf178_m1': ['activation'],
    'Xe137': ['activation', 'fp'],
    'Sn132': ['fp'],
    'U230': ['actinide'],
    'Zn70': ['activation', 'fp'],
    'Ho165': ['activation', 'fp'],
    'Nb96': ['activation', 'fp'],
    'Sc45': ['activation'],
    'Sb133': ['fp'],
    'Nb100': ['activation', 'fp'],
    'Xe126': ['activation', 'fp'],
    'Zn72': ['fp'],
    'Ru107': ['activation', 'fp'],
    'Po218': ['actinide'],
    'Gd152': ['activation', 'fp'],
    'Po213': ['actinide'],
    'Gd156': ['activation', 'fp'],
    'Pm146': ['fp'],
    'Te135': ['fp'],
    'Pm158': ['fp'],
    'Nb105': ['fp'],
    'Po211': ['actinide', 'activation'],
    'Nb93_m1': ['activation', 'fp'],
    'Pa234': ['actinide'],
    'Ni63': ['activation'],
    'Cu74': ['fp'],
    'Sm149': ['activation', 'fp'],
    'Nb98_m1': ['fp'],
    'Cl35': ['activation'],
    'Pu245': ['actinide'],
    'Xe147': ['fp'],
    'Pr149': ['fp'],
    'Ba139': ['activation', 'fp'],
    'Sm151': ['activation', 'fp'],
    'Kr85': ['activation', 'fp'],
    'Ag111_m1': ['activation', 'fp'],
    'K41': ['activation'],
    'Se88': ['fp'],
    'Pm154_m1': ['fp'],
    'Ce139_m1': ['activation'],
    'Ti47': ['activation'],
    'Os192': ['activation'],
    'Br92': ['fp'],
    'Nb103': ['fp'],
    'W185': ['activation'],
    'Gd157': ['activation', 'fp'],
    'Cs141': ['fp'],
    'Rh103_m1': ['fp'],
    'Sb127': ['fp'],
    'Ag115_m1': ['fp'],
    'Rh120': ['fp'],
    'Zr103': ['fp'],
    'Pd107_m1': ['activation', 'fp'],
    'Sr99': ['fp'],
    'I144': ['fp'],
    'Po216': ['actinide'],
    'Rh117': ['fp'],
    'Kr79': ['activation', 'fp'],
    'Np237': ['actinide'],
    'Er171': ['activation', 'fp'],
    'Pu239': ['actinide'],
    'Se83_m1': ['activation', 'fp'],
    'Pr158': ['fp'],
    'Sb121': ['activation', 'fp'],
    'U231': ['actinide'],
    'In114': ['activation', 'fp'],
    'Ni74': ['fp'],
    'W184': ['activation'],
    'Ru99': ['activation', 'fp'],
    'S36': ['activation'],
    'Tc118': ['fp'],
    'Ba148': ['fp'],
    'In130': ['fp'],
    'Te128': ['activation', 'fp'],
    'Ti48': ['activation'],
    'Er167_m1': ['activation', 'fp'],
    'Nb92': ['activation', 'fp'],
    'Ba132': ['activation', 'fp'],
    'Ir192': ['activation'],
    'Sr92': ['fp'],
    'Ne20': ['activation'],
    'Kr97': ['fp'],
    'Sn117_m1': ['activation', 'fp'],
    'Ho163': ['activation'],
    'Mo99': ['activation', 'fp'],
    'Ru117': ['fp'],
    'Co60': ['activation'],
    'Ba142': ['fp'],
    'N16': ['activation'],
    'Th233': ['actinide'],
    'Ag106': ['activation', 'fp'],
    'Gd153': ['activation', 'fp'],
    'Te121_m1': ['activation'],
    'Am246': ['actinide'],
    'Zn76': ['fp'],
    'Sr87': ['activation', 'fp'],
    'Hf179_m1': ['activation'],
    'Ru120': ['fp'],
    'Br89': ['fp'],
    'Rb90_m1': ['fp'],
    'Ga72': ['activation', 'fp'],
    'Ru110': ['fp'],
    'Ag121': ['fp'],
    'Sr90': ['activation', 'fp'],
    'Sb122': ['activation', 'fp'],
    'Er165': ['activation'],
    'Zr102': ['fp'],
    'Ga84': ['fp'],
    'Pa235': ['actinide'],
    'Sm146': ['activation', 'fp'],
    'Cf254': ['actinide'],
    'Te138': ['fp'],
    'Zn66': ['activation', 'fp'],
    'As82_m1': ['fp'],
    'Am239': ['actinide'],
    'Cm250': ['actinide'],
    'Sm162': ['fp'],
    'Gd163': ['fp'],
    'Ag119': ['fp'],
    'Ba141': ['activation', 'fp'],
    'Y93': ['activation', 'fp'],
    'Ce143': ['activation', 'fp'],
    'In120': ['activation', 'fp'],
    'Nb97': ['activation', 'fp'],
    'Co61': ['activation'],
    'Br95': ['fp'],
    'Ar39': ['activation'],
    'Se79_m1': ['activation', 'fp'],
    'Y106': ['fp'],
    'In116_m1': ['activation', 'fp'],
    'Th232': ['actinide'],
    'Pb210': ['actinide'],
    'In129': ['fp'],
    'Pd112': ['fp'],
    'Xe128': ['activation', 'fp'],
    'Te127_m1': ['activation', 'fp'],
    'Ho166': ['activation', 'fp'],
    'Pu236': ['actinide'],
    'Pm152': ['activation', 'fp'],
    'Cd127': ['fp'],
    'Yb177': ['activation'],
    'Ge73': ['activation', 'fp'],
    'Ga82': ['fp'],
    'Zr109': ['fp'],
    'Ar41': ['activation'],
    'Pa233': ['actinide'],
    'Ru106': ['activation', 'fp'],
    'Ag112': ['activation', 'fp'],
    'Ga77': ['fp'],
    'Cd130': ['fp'],
    'Ag128': ['fp'],
    'P33': ['activation'],
    'Y107': ['fp'],
    'Ce148': ['fp'],
    'Rh106_m1': ['activation', 'fp'],
    'Kr82': ['activation', 'fp'],
    'Sb137': ['fp'],
    'He4': ['actinide', 'activation'],
    'Mo96': ['activation', 'fp'],
    'Ba133_m1': ['activation'],
    'Sn134': ['fp'],
    'Ru102': ['activation', 'fp'],
    'Zr97': ['activation', 'fp'],
    'Te129': ['activation', 'fp'],
    'Zn79': ['fp'],
    'Sb128_m1': ['fp'],
    'Au200': ['activation'],
    'Np240_m1': ['actinide'],
    'Xe144': ['fp'],
    'Ge74': ['activation', 'fp'],
    'Pm145': ['activation', 'fp'],
    'Sn121': ['activation', 'fp'],
    'Kr79_m1': ['activation'],
    'Sn119_m1': ['activation', 'fp'],
    'Mo95': ['activation', 'fp'],
    'Nd151': ['activation', 'fp'],
    'Ne22': ['activation'],
    'Nd153': ['fp'],
    'La139': ['activation', 'fp'],
    'Nb111': ['fp'],
    'Y100': ['fp'],
    'Rb93': ['fp'],
    'Nd142': ['activation', 'fp'],
    'Y89_m1': ['activation', 'fp'],
    'Ar38': ['activation'],
    'Na23': ['activation'],
    'Sr89': ['activation', 'fp'],
    'Se76': ['activation', 'fp'],
    'Br81': ['activation', 'fp'],
    'Cd113_m1': ['fp'],
    'Am242_m1': ['actinide'],
    'Xe133': ['activation', 'fp'],
    'Ce137': ['activation'],
    'Rh109': ['fp'],
    'Pr151': ['fp'],
    'Rh108': ['fp'],
    'In132': ['fp'],
    'Mo105': ['fp'],
    'V53': ['activation'],
    'Hg205': ['activation'],
    'Mg26': ['activation'],
    'Cd115': ['activation', 'fp'],
    'Te129_m1': ['activation', 'fp'],
    'As82': ['fp'],
    'Pd119': ['fp'],
    'Ag118': ['fp'],
    'Se74': ['activation'],
    'Bi214': ['actinide'],
    'Pt197_m1': ['activation'],
    'Ba136_m1': ['activation', 'fp'],
    'Rh104': ['activation', 'fp'],
    'Sn112': ['activation'],
    'Cm247': ['actinide'],
    'Pr156': ['fp'],
    'Pu241': ['actinide'],
    'I129': ['activation', 'fp'],
    'Ag116_m1': ['fp'],
    'Na24': ['activation'],
    'Eu156': ['activation', 'fp'],
    'Ge75': ['activation', 'fp'],
    'Gd161': ['activation', 'fp'],
    'Cu79': ['fp'],
    'In119_m1': ['activation', 'fp'],
    'H3': ['activation', 'fp'],
    'Ge71_m1': ['activation', 'fp'],
    'Ce155': ['fp'],
    'Fr221': ['actinide'],
    'Hg196': ['activation'],
    'Nd158': ['fp'],
    'Ca49': ['activation'],
    'I137': ['fp'],
    'Hf182': ['activation'],
    'La140': ['activation', 'fp'],
    'Cl38_m1': ['activation'],
    'Zr90': ['activation', 'fp'],
    'Sn123_m1': ['activation', 'fp'],
    'Cf251': ['actinide'],
    'Zr108': ['fp'],
    'Cd106': ['activation'],
    'U236': ['actinide'],
    'H4': ['activation'],
    'Ca43': ['activation'],
    'Cs148': ['fp'],
    'La155': ['fp'],
    'Rh102': ['activation', 'fp'],
    'Fe56': ['activation'],
    'Tm169': ['activation', 'fp'],
    'Ag116': ['fp'],
    'As81': ['fp'],
    'Ni59': ['activation'],
    'Eu164': ['fp'],
    'Y92': ['activation', 'fp'],
    'Sc49': ['activation'],
    'Ag122': ['fp'],
    'Si29': ['activation'],
    'Mo97': ['activation', 'fp'],
    'Sm144': ['activation'],
    'U233': ['actinide'],
    'Cs132': ['activation', 'fp'],
    'Br79_m1': ['fp'],
    'Cr50': ['activation'],
    'Pb205': ['activation'],
    'Sn124': ['activation', 'fp'],
    'U238': ['actinide'],
    'In127_m1': ['fp'],
    'Am242': ['actinide'],
    'Sn133': ['fp'],
    'Li7': ['activation', 'fp'],
    'I127': ['activation', 'fp'],
    'Tl206': ['actinide', 'activation'],
    'Sn119': ['activation', 'fp'],
    'Pu243': ['actinide'],
    'Te120': ['activation'],
    'Ga72_m1': ['activation'],
    'Nd144': ['activation', 'fp'],
    'Os193': ['activation'],
    'Cf249': ['actinide'],
    'Ba135': ['activation', 'fp'],
    'Th228': ['actinide'],
    'Rh108_m1': ['fp'],
    'Am240': ['actinide'],
    'Pd120': ['fp'],
    'Sb132_m1': ['fp'],
    'Cd131': ['fp'],
    'Np236': ['actinide'],
    'Xe133_m1': ['activation', 'fp'],
    'Co59': ['activation'],
    'Y97': ['fp'],
    'Kr84': ['activation', 'fp'],
    'Mo93_m1': ['activation'],
    'Tc109': ['fp'],
    'Be9': ['activation', 'fp'],
    'Ge87': ['fp'],
    'Os189': ['activation'],
    'Ce147': ['fp'],
    'Xe142': ['fp'],
    'Rh105_m1': ['activation', 'fp'],
    'In121_m1': ['fp'],
    'Xe131_m1': ['activation', 'fp'],
    'Sn114': ['activation', 'fp'],
    'Rb99': ['fp'],
    'Ac227': ['actinide'],
    'Bi213': ['actinide'],
    'Ca42': ['activation'],
    'U239': ['actinide'],
    'Ac228': ['actinide'],
    'Si31': ['activation'],
    'Cd125': ['fp'],
    'Xe131': ['activation', 'fp'],
    'Ra225': ['actinide'],
    'Zn69': ['activation', 'fp'],
    'In123': ['fp'],
    'Tb160': ['activation', 'fp'],
    'Br96': ['fp'],
    'Kr89': ['fp'],
    'Pd107': ['activation', 'fp'],
    'Cu66': ['activation', 'fp'],
    'Sb124_m1': ['activation', 'fp'],
    'Pt193_m1': ['activation'],
    'Cu73': ['fp'],
    'As85': ['fp'],
    'Nd150': ['activation', 'fp'],
    'Pd122': ['fp'],
    'S34': ['activation'],
    'Zn69_m1': ['activation', 'fp'],
    'As79': ['fp'],
    'Br91': ['fp'],
    'In118': ['activation', 'fp'],
    'Pd115': ['fp'],
    'Pr153': ['fp'],
    'Ba131': ['activation'],
    'Te133_m1': ['fp'],
    'Sn121_m1': ['activation', 'fp'],
    'Ce153': ['fp'],
    'Zn71': ['activation', 'fp'],
    'Kr86': ['activation', 'fp'],
    'Cu76': ['fp'],
    'Ge84': ['fp'],
    'Xe125': ['activation'],
    'Ru118': ['fp'],
    'Al28': ['activation'],
    'Xe139': ['fp'],
    'Nd161': ['fp'],
    'Ge77': ['activation', 'fp'],
    'Cd117_m1': ['activation', 'fp'],
    'Sb135': ['fp'],
    'Pd116': ['fp'],
    'Tb162_m1': ['fp'],
    'Cd119_m1': ['fp'],
    'I125': ['activation'],
    'P31': ['activation'],
    'Br86': ['fp'],
    'Sn120': ['activation', 'fp'],
    'Pu237': ['actinide'],
    'Cu80': ['fp'],
    'La149': ['fp'],
    'Ag108_m1': ['activation', 'fp'],
    'Sn128': ['fp'],
    'Tc101': ['activation', 'fp'],
    'Ni65': ['activation'],
    'O18': ['activation'],
    'Tc110': ['fp'],
    'Tl205': ['activation'],
    'Cd112': ['activation', 'fp'],
    'Po215': ['actinide'],
    'Bk250': ['actinide'],
    'Yb170': ['activation', 'fp'],
    'Ce137_m1': ['activation'],
    'Hg202': ['activation'],
    'Hf180_m1': ['activation'],
    'Ra222': ['actinide'],
    'Er169': ['activation', 'fp'],
    'Np235': ['actinide'],
    'Dy159': ['activation'],
    'Al27': ['activation'],
    'Ni72': ['fp'],
    'Fe54': ['activation'],
    'As88': ['fp'],
    'Ag123': ['fp'],
    'Kr88': ['activation', 'fp'],
    'P34': ['activation'],
    'Hg199': ['activation'],
    'Ce157': ['fp'],
    'Nb112': ['fp'],
    'Ru100': ['activation', 'fp'],
    'Pm151': ['activation', 'fp'],
    'Y90': ['activation', 'fp'],
    'Zn77': ['fp'],
    'Co62': ['activation'],
    'I126': ['activation'],
    'Cd129': ['fp'],
    'Nb109': ['fp'],
    'Xe138': ['fp'],
    'Am245': ['actinide'],
    'Te137': ['fp'],
    'Cs140': ['fp'],
    'Nd141': ['fp'],
    'Tc116': ['fp'],
    'Ar40': ['activation'],
    'Zn73': ['fp'],
    'Ga80': ['fp'],
    'Hf174': ['activation'],
    'Cr51': ['activation'],
    'Re186': ['activation'],
    'Ce144': ['activation', 'fp'],
    'Ni66': ['activation', 'fp'],
    'Tc105': ['fp'],
    'Pr146': ['fp'],
    'Br82': ['activation', 'fp'],
    'W187': ['activation'],
    'Ba140': ['activation', 'fp'],
    'Cm249': ['actinide'],
    'Te140': ['fp'],
    'Na22': ['activation'],
    'Fe57': ['activation'],
    'K42': ['activation'],
    'Pm155': ['fp'],
    'Ba130': ['activation'],
    'Am244_m1': ['actinide'],
    'Sn118': ['activation', 'fp'],
    'Pr140': ['fp'],
    'Ga79': ['fp'],
    'Te136': ['fp'],
    'Pd109_m1': ['activation', 'fp'],
    'Th231': ['actinide'],
    'I132': ['activation', 'fp'],
    'Rn222': ['actinide'],
    'Br80_m1': ['activation', 'fp'],
    'Dy161': ['activation', 'fp'],
    'Dy156': ['activation'],
    'Ne23': ['activation'],
    'Pm148_m1': ['activation', 'fp'],
    'Sn123': ['activation', 'fp'],
    'Pd102': ['activation', 'fp'],
    'Nd149': ['activation', 'fp'],
    'Tb163': ['fp'],
    'Xe127_m1': ['activation'],
    'In116': ['activation', 'fp'],
    'Pb208': ['actinide', 'activation'],
    'Xe127': ['activation', 'fp'],
    'Ce150': ['fp'],
    'Eu151': ['activation', 'fp'],
    'Ga69': ['activation', 'fp'],
    'Cd119': ['activation', 'fp'],
    'Nb91': ['activation', 'fp'],
    'Y103': ['fp'],
    'Hg197': ['activation'],
    'I140': ['fp'],
    'Y99': ['fp'],
    'V51': ['activation'],
    'Tc117': ['fp'],
    'Rn218': ['actinide'],
    'Pr145': ['activation', 'fp'],
    'Rh113': ['fp'],
    'Pt192': ['activation'],
    'Ga70': ['activation', 'fp'],
    'Pd106': ['activation', 'fp'],
    'Se81': ['activation', 'fp'],
    'Pt190': ['activation'],
    'Pd121': ['fp'],
    'Ni78': ['fp'],
    'W183': ['activation'],
    'Fr223': ['actinide'],
    'Gd155': ['activation', 'fp'],
    'In133': ['fp'],
    'Os190_m1': ['activation'],
    'Xe134': ['activation', 'fp'],
    'I134_m1': ['fp'],
    'Pr152': ['fp'],
    'Te133': ['fp'],
    'Th234': ['actinide'],
    'Y102': ['fp'],
    'Au198': ['activation'],
    'V49': ['activation'],
    'Eu150': ['fp'],
    'Ce151': ['fp'],
    'At217': ['actinide'],
    'As90': ['fp'],
    'Hf175': ['activation'],
    'O19': ['activation'],
    'Bi209': ['actinide', 'activation'],
    'Xe143': ['fp'],
    'Re189': ['activation'],
    'Cm248': ['actinide'],
    'La144': ['fp'],
    'Cd122': ['fp'],
    'Cf252': ['actinide'],
    'Kr78': ['activation'],
    'Se83': ['activation', 'fp'],
    'Tc106': ['fp'],
    'Ru111': ['fp'],
    'Sn115': ['activation', 'fp'],
    'I130': ['activation', 'fp'],
    'Te130': ['activation', 'fp'],
    'Th226': ['actinide'],
    'Ru116': ['fp'],
    'In115_m1': ['fp'],
    'Ni62': ['activation'],
    'I133_m1': ['fp'],
    'Sm153': ['activation', 'fp'],
    'Kr96': ['fp'],
    'Rb97': ['fp'],
    'Pa232': ['actinide'],
    'Sr87_m1': ['activation', 'fp'],
    'Ge72': ['activation', 'fp'],
    'I130_m1': ['activation', 'fp'],
    'Mo115': ['fp'],
    'Gd164': ['fp'],
    'Cd111': ['activation', 'fp'],
    'Ru108': ['fp'],
    'Yb176': ['activation'],
    'Ge77_m1': ['activation', 'fp'],
    'Se84': ['fp'],
    'Mn58': ['activation'],
    'Mo101': ['activation', 'fp'],
    'Ru103': ['activation', 'fp'],
    'Be10': ['activation', 'fp'],
    'In113': ['activation', 'fp'],
    'Tc98': ['activation', 'fp'],
    'Os187': ['activation'],
    'N13': ['activation'],
    'La147': ['fp'],
    'Os188': ['activation'],
    'Cd107': ['activation'],
    'Pt198': ['activation'],
    'Zn68': ['activation', 'fp'],
    'Er166': ['activation', 'fp'],
    'Po212': ['actinide'],
    'In134': ['fp'],
    'Rb95': ['fp'],
    'Pr144': ['activation', 'fp'],
    'Cs136': ['activation', 'fp'],
    'Te126': ['activation', 'fp'],
    'Pm162': ['fp'],
    'He6': ['activation'],
    'Se75': ['activation'],
    'Y98': ['fp'],
    'C14': ['activation', 'fp'],
    'Pd123': ['fp'],
    'Cd117': ['activation', 'fp'],
    'Te121': ['activation'],
    'Ce152': ['fp'],
    'Hg197_m1': ['activation'],
    'Pm149': ['activation', 'fp'],
    'Sm155': ['activation', 'fp'],
    'Ru115': ['fp'],
    'Cs145': ['fp'],
    'Si32': ['activation'],
    'Cl38': ['activation'],
    'Se89': ['fp'],
    'U234': ['actinide'],
    'Tb161': ['activation', 'fp'],
    'Tl207': ['actinide'],
    'Cm246': ['actinide'],
    'Ar37': ['activation'],
    'Cd121': ['activation', 'fp'],
    'Nb97_m1': ['activation', 'fp'],
    'Tc103': ['fp'],
    'La143': ['fp'],
    'Rb101': ['fp'],
    'Co74': ['fp'],
    'Pr139': ['fp'],
    'Ba134': ['activation', 'fp'],
    'Sb139': ['fp'],
    'Ir193': ['activation'],
    'Kr83_m1': ['activation', 'fp'],
    'Ne21': ['activation'],
    'Nd155': ['fp'],
    'Ce141': ['activation', 'fp'],
    'Ag113_m1': ['fp'],
    'Sn127': ['fp'],
    'Zn80': ['fp'],
    'Sb122_m1': ['activation', 'fp'],
    'Bi210': ['actinide', 'activation'],
    'Al30': ['activation'],
    'Xe135': ['activation', 'fp'],
    'Eu152_m1': ['activation', 'fp'],
    'Rn220': ['actinide'],
    'Po214': ['actinide'],
    'Tm171': ['activation', 'fp'],
    'Sm165': ['fp'],
    'Pt194': ['activation'],
    'Rh116': ['fp'],
    'Pu238': ['actinide'],
    'Sn116': ['activation', 'fp'],
    'Ni73': ['fp'],
    'Sr85': ['activation'],
    'Pt196': ['activation'],
    'Ag113': ['fp'],
    'Ce139': ['activation', 'fp'],
    'Ba137_m1': ['activation', 'fp'],
    'Xe145': ['fp'],
    'Es254': ['actinide'],
    'Y94': ['activation', 'fp'],
    'W183_m1': ['activation'],
    'Ge81': ['fp'],
    'Zr90_m1': ['fp'],
    'Hf176': ['activation'],
    'Nd160': ['fp'],
    'Ge71': ['activation', 'fp'],
    'Sm145': ['activation', 'fp'],
    'Lu175': ['activation'],
    'Cu81': ['fp'],
    'S35': ['activation'],
    'N15': ['activation'],
    'Te131': ['activation', 'fp'],
    'In125': ['fp'],
    'B11': ['activation'],
    'Cd109': ['activation', 'fp'],
    'Sn129': ['fp'],
    'Ba149': ['fp'],
    'Co75': ['fp'],
    'Ti51': ['activation'],
    'Sb129': ['fp'],
    'Ge75_m1': ['activation', 'fp'],
    'Au197': ['activation'],
    'Nb108': ['fp'],
    'Rb92': ['fp'],
    'Cr55': ['activation'],
    'Kr87': ['activation', 'fp'],
    'Y105': ['fp'],
    'Cs143': ['fp'],
    'Cm243': ['actinide'],
    'Hg199_m1': ['activation'],
    'Nb94_m1': ['fp'],
    'Ar36': ['activation'],
    'Lu177': ['activation'],
    'Pt191': ['activation'],
    'In128': ['fp'],
    'Pd111_m1': ['activation', 'fp'],
    'Pr142': ['activation', 'fp'],
    'Gd158': ['activation', 'fp'],
    'Hg201': ['activation'],
    'I128': ['activation', 'fp'],
    'Ag127': ['fp'],
    'Cd126': ['fp'],
    'Ga83': ['fp'],
    'Nb98': ['activation', 'fp'],
    'Cs138_m1': ['fp'],
    'Eu158': ['fp'],
    'Se81_m1': ['activation', 'fp'],
    'Co73': ['fp'],
    'Cs135': ['activation', 'fp'],
    'Rb88': ['activation', 'fp'],
    'Pt195_m1': ['activation'],
    'Pu244': ['actinide'],
    'Ba147': ['fp'],
    'Ge82': ['fp'],
    'Ir191': ['activation'],
    'Rb85': ['activation', 'fp'],
    'Pm148': ['activation', 'fp'],
    'Te134': ['fp'],
    'Ag110': ['activation', 'fp'],
    'Cd108': ['activation', 'fp'],
    'Bi212': ['actinide'],
    'Gd165': ['fp'],
    'Se80': ['activation', 'fp'],
    'Br84': ['fp'],
    'Sm152': ['activation', 'fp'],
    'Tm172': ['activation', 'fp'],
    'Tc99': ['activation', 'fp'],
    'Pm154': ['fp'],
    'Te123_m1': ['activation', 'fp'],
    'Tc100': ['activation', 'fp'],
    'Ce156': ['fp'],
    'Nb104': ['fp'],
    'Ag117_m1': ['fp'],
    'Cu63': ['activation'],
    'Lu176': ['activation'],
    'As75': ['activation', 'fp'],
    'Sb136': ['fp'],
    'Pm150': ['activation', 'fp'],
    'In121': ['activation', 'fp'],
    'Xe141': ['fp'],
    'Co60_m1': ['activation'],
    'Ag111': ['activation', 'fp'],
    'In119': ['activation', 'fp'],
    'Cd113': ['activation', 'fp'],
    'Ir192_m1': ['activation'],
    'Tl209': ['actinide'],
    'Sr104': ['fp'],
    'Nb106': ['fp'],
    'Ta182_m1': ['activation'],
    'Mo112': ['fp'],
    'Cs146': ['fp'],
    'Rh119': ['fp'],
    'Hg200': ['activation'],
    'Y95': ['fp'],
    'In120_m1': ['activation', 'fp'],
    'La150': ['fp'],
    'V52': ['activation'],
    'Sr88': ['activation', 'fp'],
    'Sr103': ['fp'],
    'Si28': ['activation'],
    'Cu64': ['activation'],
    'Pd117': ['fp'],
    'La153': ['fp'],
    'Ca44': ['activation'],
    'Ru119': ['fp'],
    'Pm160': ['fp'],
    'Pm147': ['activation', 'fp'],
    'Zn65': ['activation'],
    'Se90': ['fp'],
    'Eu160': ['fp'],
    'Eu159': ['fp'],
    'Dy162': ['activation', 'fp'],
    'Rh114': ['fp'],
    'Xe140': ['fp'],
    'Te124': ['activation', 'fp'],
    'Cd116': ['activation', 'fp'],
    'Br84_m1': ['fp'],
    'Pr148': ['fp'],
    'U240': ['actinide'],
    'Cu67': ['activation', 'fp'],
    'Cm242': ['actinide'],
    'Mg28': ['activation'],
    'Kr80': ['activation', 'fp'],
    'Cs134': ['activation', 'fp'],
    'Nb95_m1': ['activation', 'fp'],
    'Ru104': ['activation', 'fp'],
    'Pu242': ['actinide'],
    'Pt195': ['activation'],
    'Bi211': ['actinide', 'activation'],
    'Zr89': ['activation'],
    'Es253': ['actinide'],
    'Br94': ['fp'],
    'Es255': ['actinide'],
    'He3': ['activation'],
    'Mg25': ['activation'],
    'S33': ['activation'],
    'Sn130': ['fp'],
    'Zr100': ['fp'],
    'Pd108': ['activation', 'fp'],
    'Zr99': ['fp'],
    'Sr91': ['activation', 'fp'],
    'B12': ['activation'],
    'Cu78': ['fp'],
    'Ba138': ['activation', 'fp'],
    'Xe134_m1': ['fp'],
    'Li8': ['activation'],
    'Hg198': ['activation'],
    'Br79': ['activation', 'fp'],
    'Yb172': ['activation', 'fp'],
    'Sc50': ['activation'],
    'Mo108': ['fp'],
    'Os191': ['activation'],
    'Pd124': ['fp'],
    'Tc97': ['activation'],
    'Se78': ['activation', 'fp'],
    'Cd114': ['activation', 'fp'],
    'Cs150': ['fp'],
    'Ca45': ['activation'],
    'Ag108': ['activation', 'fp'],
    'Pd118': ['fp'],
    'In122_m1': ['fp'],
    'V50': ['activation'],
    'Ba135_m1': ['activation', 'fp'],
    'Nb99': ['fp'],
    'Er164': ['activation'],
    'Sb128': ['fp'],
    'Zn74': ['fp'],
    'Pd125': ['fp'],
    'Y96': ['activation', 'fp'],
    'Th229': ['actinide'],
    'Sm154': ['activation', 'fp'],
    'Tm170_m1': ['activation', 'fp'],
    'Zr92': ['activation', 'fp'],
    'Re187': ['activation'],
    'Ni61': ['activation'],
    'S250': ['actinide'],
    'Pt199_m1': ['activation'],
    'Hg203': ['activation'],
    'Br90': ['fp'],
    'Np239': ['actinide'],
    'Zn63': ['activation'],
    'Te141': ['fp'],
    'Ba131_m1': ['activation'],
    'Tc113': ['fp'],
    'Yb175': ['activation'],
    'Eu157': ['fp'],
    'As76': ['activation', 'fp'],
    'Se85_m1': ['fp'],
    'Xe130': ['activation', 'fp'],
    'Dy165': ['activation', 'fp'],
    'Hf181': ['activation'],
    'I139': ['fp'],
    'Sn125_m1': ['activation', 'fp'],
    'Rh111': ['fp'],
    'Na25': ['activation'],
    'Nb95': ['activation', 'fp'],
    'In115': ['activation', 'fp'],
    'Ag124': ['fp'],
    'In114_m1': ['activation', 'fp'],
    'Cs133': ['activation', 'fp'],
    'Yb169': ['activation', 'fp'],
    'Br87': ['fp'],
    'Cd118': ['fp'],
    'Rh118': ['fp'],
    'Rb86': ['activation', 'fp'],
    'Pm157': ['fp'],
    'Cs144': ['fp'],
    'Ta181': ['activation'],
    'Pd126': ['fp'],
    'Zn75': ['fp'],
    'Nb94': ['activation', 'fp'],
    'K39': ['activation'],
    'Ru112': ['fp'],
    'Cu62': ['activation'],
    'Zn83': ['fp'],
    'Mn54': ['activation'],
    'Ti46': ['activation'],
    'Ag120': ['fp'],
    'Pu246': ['actinide'],
    'Np240': ['actinide'],
    'Br88': ['fp'],
    'Zr107': ['fp'],
    'Ra226': ['actinide'],
    'Zn82': ['fp'],
    'Mn56': ['activation'],
    'Mo98': ['activation', 'fp'],
    'Re185': ['activation'],
    'Np238': ['actinide'],
    'Y89': ['activation', 'fp'],
    'Cs139': ['fp'],
    'Zr94': ['activation', 'fp'],
    'Mo100': ['activation', 'fp'],
    'Sm150': ['activation', 'fp'],
    'Ge80': ['fp'],
    'Sn126': ['fp'],
    'Mo114': ['fp'],
    'Pd105': ['activation', 'fp'],
    'Tc97_m1': ['activation'],
    'Pm159': ['fp'],
    'U232': ['actinide'],
    'S32': ['activation'],
    'Rh122': ['fp'],
    'Cd123': ['fp'],
    'Tm173': ['activation'],
    'Ti49': ['activation'],
    'Cm251': ['actinide'],
    'Sr98': ['fp'],
    'B10': ['activation'],
    'Tc102_m1': ['fp'],
    'Rb100': ['fp'],
    'Zr106': ['fp'],
    'Rh105': ['activation', 'fp'],
    'Y91_m1': ['fp'],
    'Se77': ['activation', 'fp'],
    'Zr101': ['fp'],
    'Gd162': ['activation', 'fp'],
    'Mg24': ['activation'],
    'Te142': ['fp'],
    'Tc112': ['fp'],
    'U237': ['actinide'],
    'In127': ['fp'],
    'Te132': ['fp'],
    'Sb138': ['fp'],
    'Ta182': ['activation'],
    'Ce146': ['fp'],
    'Pd113': ['fp'],
    'Ag118_m1': ['fp'],
    'Nd156': ['fp'],
    'Ru101': ['activation', 'fp'],
    'Te125': ['activation', 'fp'],
    'Sb126': ['activation', 'fp'],
    'Ce154': ['fp'],
    'La146': ['fp'],
    'Pd103': ['activation'],
    'Rb94': ['fp'],
    'Hf177': ['activation'],
    'Mo104': ['fp'],
    'Sc48': ['activation'],
    'Sr84': ['activation'],
    'Y90_m1': ['activation', 'fp'],
    'As86': ['fp'],
    'Sm158': ['fp'],
    'Na24_m1': ['activation'],
    'Rb98': ['fp'],
    'In113_m1': ['activation', 'fp'],
    'Po211_m1': ['actinide', 'activation'],
    'Ru113': ['fp'],
    'Es254_m1': ['actinide'],
    'Xe136': ['activation', 'fp'],
    'Se85': ['fp'],
    'In117_m1': ['activation', 'fp'],
    'H2': ['activation'],
    'W180': ['activation'],
    'Kr94': ['fp'],
    'Sm163': ['fp'],
    'Lu177_m1': ['activation'],
    'I143': ['fp'],
    'Pd114': ['fp'],
    'As80': ['fp'],
    'Np236_m1': ['actinide'],
    'W189': ['activation'],
    'Pa231': ['actinide'],
    'Sr102': ['fp'],
    'In122': ['fp'],
    'Te122': ['activation', 'fp'],
    'Rb91': ['fp'],
    'Ga81': ['fp'],
    'Pr155': ['fp'],
    'Eu155': ['activation', 'fp'],
    'La152': ['fp'],
    'Ni64': ['activation'],
    'Yb173': ['activation'],
    'Zr95': ['activation', 'fp'],
    'Ge76': ['activation', 'fp'],
    'Ra223': ['actinide'],
    'Cs131': ['activation'],
    'Eu154': ['activation', 'fp'],
    'Dy160': ['activation', 'fp'],
    'Tl208': ['actinide'],
    'Nd146': ['activation', 'fp'],
    'Co72': ['fp'],
    'Ag125': ['fp'],
    'Ag107': ['activation', 'fp'],
    'Ir194': ['activation'],
    'Tb163_m1': ['fp'],
    'As87': ['fp'],
    'Tc114': ['fp'],
    'Re188_m1': ['activation'],
    'Sb124': ['activation', 'fp'],
    'Tc107': ['fp'],
    'La142': ['fp'],
    'Br83': ['activation', 'fp'],
    'Rh110_m1': ['fp'],
    'Ce149': ['fp'],
    'Cr53': ['activation'],
    'Ru96': ['activation'],
    'Pr142_m1': ['activation', 'fp'],
    'Y91': ['activation', 'fp'],
    'Mo109': ['fp'],
    'Cf253': ['actinide'],
    'Ge79': ['fp'],
    'Ca46': ['activation'],
    'Cs137': ['activation', 'fp'],
    'Dy163': ['activation', 'fp'],
    'I142': ['fp'],
    'Te131_m1': ['activation', 'fp'],
    'Ni76': ['fp'],
    'Kr81': ['activation', 'fp'],
    'Zr98': ['fp'],
    'In118_m1': ['fp'],
    'Ag109': ['activation', 'fp'],
    'O16': ['activation'],
    'Os186': ['activation'],
    'I133': ['fp'],
    'I131': ['activation', 'fp'],
    'Ho166_m1': ['activation', 'fp'],
    'Rh107': ['activation', 'fp'],
    'Mo111': ['fp'],
    'Sr101': ['fp'],
    'Kr98': ['fp'],
    'Li6': ['activation', 'fp'],
    'Ce142': ['activation', 'fp'],
    'U241': ['actinide']
}

# Convert to the more useful format
ORIGEN_ISO_DECAY_TYPES = {"activation": set(), "actinide": set(), "fp": set()}

for iso, types in ORIGEN_ISO_DECAY_TYPES_FROM_SRC.items():
    for type_ in ORIGEN_ISO_DECAY_TYPES.keys():
        if type_ in types:
            ORIGEN_ISO_DECAY_TYPES[type_].add(iso)
